apiVersion: v2
name: technitium
description: A Helm chart for Technitium DNS Server
type: application
version: 15.0.1
appVersion: "15.0.1"
keywords:
  - dns
  - technitium
  - adblock
maintainers:
  - name: gathered-from-compose
icon: https://technitium.com/img/logo25x25.png
sources:
  - https://github.com/TechnitiumSoftware/DnsServer
